CREATE DATABASE QSDECOR_MANAGEMENT
GO

USE QSDECOR_MANAGEMENT
GO

/*TABLE AREA*/
--TABLE INCLUDES ACCOUNT INFORMATION
CREATE TABLE tbl_account
(
	ACCOUNT_ID INT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(255),
	USERNAME VARCHAR(255),
	PASSWORD VARCHAR(255),
	LEVEL INT
)
GO

--TABLE INCLUDES COLLABORATOR INFORMATION
CREATE TABLE tbl_collaborator
(
	COLLAB_ID VARCHAR(255) PRIMARY KEY,
	COLLAB_NAME VARCHAR(255),
	COLLAB_PHONE VARCHAR(255),
	COLLAB_ZALO VARCHAR(255),
	COLLAB_EMAIL VARCHAR(255),
	COLLAB_CCCD VARCHAR(255),
	COLLAB_BANK_NAME VARCHAR(255),
	COLLAB_BANK_NUMBER VARCHAR(255)
)

--TABLE INCLUDES ORDER INFORMATION
CREATE TABLE tbl_order
(
	ORDER_ID VARCHAR(255) PRIMARY KEY,
	PRODUCT_QUAN_PRICE TEXT,
	SELL_CHANEL VARCHAR(255),

	COLLAB_ID VARCHAR(255),
	
	CUSTOMER_NAME VARCHAR(255),
	CUSTOMER_PHONE VARCHAR(255),
	CUSTOMER_ADDRESS VARCHAR(255),

	SELL_PRICE FLOAT,
	SHIPPING_FEE FLOAT,
	OTHERS_FEE FLOAT,
	PAYMENT FLOAT,
	DEPOSIT FLOAT,
	BALANCE FLOAT,
	NOTE TEXT,
	ORDER_DATE DATE,
	STATUS_ORDER VARCHAR(255) DEFAULT 'PENDING',
	FOREIGN KEY(COLLAB_ID) REFERENCES tbl_collaborator(COLLAB_ID)
)
